services:
  app:
    build:
      context: .
      network: host
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
