services:
  app:
    build:
      context: .
      network: host
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-2hmwpbZp2qAkMGUE0WygL38_JVws4tms}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dK9AI1M8VvZ7XtVu8TYTVKhBZoVCE1s2}
